Freetype wps
Universebenzene/benzene-overlay pull request #1
Opened 2024-02-28 09:05 UTC by 123485k

添加了专门为wps的freetype 2.13.0版本

2024-02-28 13:58 UTC, Universebenzene requested changes

2024-02-28 13:58 UTC, Universebenzene commented on media-libs/freetype-wps/freetype-wps-2.13.0.ebuild
> +# Copyright 1999-2023 Gentoo Authors
header可以更新到2024

2024-02-28 13:58 UTC, Universebenzene commented on app-office/wps-office/wps-office-11.1.0.11719-r1.ebuild
> +	!syetem-freetype? ( media-libs/freetype-wps )
你system拼错了
另外底下也加上一句 `system-freetype? ( media-libs/freetype:2 )` 罢

2024-02-28 13:58 UTC, Universebenzene commented
大佬你这个freetype-wps没有规避和新版freetype的文件冲突啊，你打完包之后在本地好好测试过没？

2024-02-28 14:24 UTC, 123485k commented
> 大佬你这个freetype-wps没有完全规避和新版freetype的文件冲突，还剩了一个/usr/share/aclocal的东西

等我优化一下，看了一下还是重新写个ebuild比较划算一点

2024-02-28 16:02 UTC, 123485k commented
修复好了，重写了src_install,上面提到的问题也修复了

2024-02-28 18:07 UTC, Universebenzene commented
> 修复好了，重写了src_install,上面提到的问题也修复了

呃，system拼错了的问题还没解决

2024-02-28 19:32 UTC, Universebenzene commented
不是你怎么又给拼成sysetem了……明明usedesc拼对了啊……

2024-02-29 02:27 UTC, Universebenzene commented on media-libs/freetype-wps/freetype-wps-2.13.0.ebuild
> +
这个空行里是不是有个tab，删掉罢

另外我建议你下次提交之前本地先跑下 `pkgcheck scan` 比较好

2024-02-29 02:29 UTC, Universebenzene commented on media-libs/freetype-wps/freetype-wps-2.13.0.ebuild
> +		LIBPNG_CFLAGS="$($(tc-getPKG_CONFIG) --cflags libpng)"
tc-getPKG_CONFIG是属于toolchain-function里定义的function，你开头没有inherit

2024-03-04 02:53 UTC, Universebenzene commented
@123485k 我昨天给wps的ebuild修改了一下，现在出conflict了，大佬应该要跟进一下

2024-03-04 14:47 UTC, closed without merging